#!/bin/sh

# Copy last commit hash to clipboard on commit
git log -1 --format=format:%h | pbcopy

API_KEY=B63M9UNHo02jp01JARVuAaTGbpkIZaxq3R4SaF2s

# REQUIRED FIELDS - Today's date and commit message
MESSAGE=$(git log -1 HEAD --pretty=format:%s)
DATE_TODAY=$(date +"%Y-%m-%d %H:%M:%S")

# OPTIONAL - Label
LABEL='code commit'

REPO=${$(git remote show -n origin | grep "Push  URL" | cut -d: -f3)%.git}

curl --data-urlencode "key=$API_KEY" \
     --data-urlencode "highlight_date=$DATE_TODAY" \
     --data-urlencode "description=$REPO | $MESSAGE" \
     --data-urlencode "source=$LABEL" \
     https://www.rescuetime.com/anapi/highlights_post
